get http://localhost:8080/food-list

###

get http://localhost:8080/food-list/salmon

###

post http://localhost:8080/food-list
Content-Type: application/json

{
  "name":"banana",
  "weight": null,
  "quantity": 1,
  "macros": {
      "protein": 1,
      "carbs": 28,
      "fat": 0,
      "calories": 110
    }
}

###

delete http://localhost:8080/food-list/oats

###

put http://localhost:8080/food-list/chicken/protein/27

###

put http://localhost:8080/food-list/chicken/carbs/0

###
put http://localhost:8080/food-list/chicken/fat/0