get http://localhost:8080/food-list

###

get http://localhost:8080/food-list/salmon

###

post http://localhost:8080/food-list
Content-Type: application/json

{
  "name":"banana",
  "weight": null,
  "quantity": 1,
  "macros": {
      "protein": 1,
      "carbs": 28,
      "fat": 0,
      "calories": 110
    }
}

###

delete http://localhost:8080/food-list/oats

###

put http://localhost:8080/food-list/chicken/protein/27

###

put http://localhost:8080/food-list/chicken/carbs/0

###
put http://localhost:8080/food-list/chicken/fat/0

###
put https://foodtrackbackend.herokuapp.com/food-list/New/fat/0

###
post http://localhost:8080/users 
Content-Type: application/json

{
  "username": "deregister",
  "password": "12345",
  "email": "email@emial.com"
}

###
post https://foodtrackbackend.herokuapp.com/users
Content-Type: application/json

{
  "username": "deregister",
  "password": "12345",
  "email": "email@emial.com"
}

###
get http://localhost:8080/users/tester1

###

put http://localhost:8080/users/tester
Content-Type: application/json

{
  "username": "tester1",
  "password": "1234",
  "email": "hola@gmail.com"
}

###
post http://localhost:8080/users/:username/meals/:foodId
Content-Type: application/json

{
  "username":"tester1",
  "meals": "627d1c2833939a9134e31d3f"
}

###

delete http://localhost:8080/users/:username/meals/:foodId
Content-Type: application/json

{
  "username":"tester1",
  "meals": "627d1c2833939a9134e31d3f"
}

###
delete http://localhost:8080/users/:username
Content-Type: application/json

{
  "username": "deregister"
}